# Generated by Django 3.2.8 on 2021-10-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('confirmpassword', models.TextField()),
            ],
        ),
    ]
