# Generated by Django 3.2.8 on 2021-10-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='name',
            new_name='username',
        ),
    ]
